services:
  frontend:
    build: ./frontend
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"
    # stdin_open : true
    # tty : true
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://paidivibhavanrao198135pvr:198135@samplecluster.8f7yw.mongodb.net/user?retryWrites=true&w=majority&appName=sampleCluster
      - PORT=5000
      - JWT_SECRET=mySuperSecretKey198135